import {
    getMarkdownTheme,
    keyText,
    type EntryRenderer,
    type ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import { Box, Markdown, Spacer, Text } from "@earendil-works/pi-tui";

import {
    PORTABLE_SUMMARY_CUSTOM_TYPE,
    parsePortableSummaryRecord,
    type PortableSummaryRecordV1,
} from "./portable-record.ts";

export type PortableSummaryDisplay = {
    summary: string;
    entryCount: number;
    provider: string;
    modelId: string;
};

export function describePortableSummaryForDisplay(data: unknown): PortableSummaryDisplay | undefined {
    let record: PortableSummaryRecordV1;
    try {
        record = parsePortableSummaryRecord(data);
    } catch {
        return undefined;
    }
    if (record.state !== "complete" || record.step.kind !== "summary-call" || record.summary === null) {
        return undefined;
    }
    return {
        summary: record.summary,
        entryCount: record.range.entryCount,
        provider: record.step.summarizer.provider,
        modelId: record.step.summarizer.modelId,
    };
}

const renderPortableSummaryEntry: EntryRenderer = (entry, { expanded }, theme) => {
    const display = describePortableSummaryForDisplay(entry.data);
    if (!display) return undefined;

    const box = new Box(1, 1, (text) => theme.bg("customMessageBg", text));
    const label = theme.fg("customMessageLabel", theme.bold("[portable compaction]"));
    box.addChild(new Text(label, 0, 0));
    box.addChild(new Spacer(1));

    const entryLabel = display.entryCount === 1 ? "entry" : "entries";
    if (expanded) {
        const header = [
            `**Portable summary of ${display.entryCount.toLocaleString()} visible ${entryLabel}**`,
            `Generated by ${display.provider}/${display.modelId}`,
            "",
            display.summary,
        ].join("\n\n");
        box.addChild(new Markdown(header, 0, 0, getMarkdownTheme(), {
            color: (text) => theme.fg("customMessageText", text),
        }));
    } else {
        const text = `Summarized ${display.entryCount.toLocaleString()} visible ${entryLabel} for non-Codex models (`;
        box.addChild(new Text(
            theme.fg("customMessageText", text)
            + theme.fg("dim", keyText("app.tools.expand"))
            + theme.fg("customMessageText", " to expand)"),
            0,
            0,
        ));
    }
    return box;
};

export function registerPortableSummaryEntryRenderer(pi: ExtensionAPI): void {
    pi.registerEntryRenderer(PORTABLE_SUMMARY_CUSTOM_TYPE, renderPortableSummaryEntry);
}
